name: dagger
on: [push, workflow_dispatch]
jobs:
  dagger:
    name: dagger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - uses: polarsignals/gh-actions-ps-profiling@v0.0.1
        with:
          polarsignals_cloud_token: ${{ secrets.PSToken }}
      - run: go run ci/ci.go test

